### ISSUE TITLE
Mod already exists. 

### ISSUE THREAD

**Issue by SoopCanSam** [LaChips/AutoCompanyBuilding#1]
This mod already exists: https://thunderstore.io/c/lethal-company/p/blink9803/AutoFlyToCompany/

Does your mod improve on this somehow?

**Comment by LaChips** [comment]
I didn't find this mod when searching for duplicates. Thanks for letting me know.

After reading the mod source code, it seems that it kinda forces you to fly to The Company Building (I might be wrong).
My mod aim to prevent accidental fly to a moon on the last day (if you forget to reroute manually), you can still change destination with the terminal if you really want to.

The ability to reroute manually is coming in the next minor update.

**Comment by DeathWrench** [comment]
Last I tried it, AutoFlyToCompany is broken in that if you're not host, and the host also doesn't have the mod, it will just land without routing.

**Comment by LaChips** [comment]
I have yet to try with multiple players but there shouldn't be any major issue.

**Comment by SoopCanSam** [comment]
Well it sounds like your mod is probably better then. Also, the other mod hasn't been updated in 2 months. I'll try yours out instead.
