### ISSUE TITLE
Autopilots on player join

### ISSUE THREAD

**Issue by darkanx** [LaChips/AutoCompanyBuilding#2]
Using Advanced Company, when a player joins a game the autopilot kicks in. I figure this is likely an issue easily dealt with by ensuring only the host has the mod on, but a check only allowing the script to execute for the host would be nice.

**Comment by LaChips** [comment]
Thanks for your feedback.

I’ll update with a fix ASAP.

**Comment by LaChips** [comment]
Fixed in v1.1.1 ([commit](https://github.com/LaChips/AutoCompanyBuilding/commit/f71a347eef5be70f46f787e0b14b9ff6977432d2))
