### ISSUE TITLE
[Request] config option to disable terminal output to the console

### ISSUE THREAD

**Issue by JohnMetroid** [LaChips/AutoCompanyBuilding#3]
Hey there, the auto company routing is very convenient

Would it be possible to get a config option that disables console output of the terminal text every time a player types a command?

Thanks for the consideration

**Comment by LaChips** [comment]
The logs were there for a possible future feature. I removed them entirely in the new build.

Fixed in version 1.1.3 ([commit](https://github.com/LaChips/AutoCompanyBuilding/commit/c8bf0c78c882dee7b98c677675de17a17ba4baab))
